% function [best, fitInfo] = SteeringSynthesis(car, Result)
% %-------------------------------------------------------------
% % Synthesizes a rack/tie-rod/steering-arm mechanism that best
% % reproduces the target delta_fi / delta_fo curves from the vehicle
% % solver, in a least-squares sense.
% %
% % FIXED (not solved for - come from suspension/rack design):
% %   a = car.t2   distance between steering-arm fixed pivots
% %   r = car.r    rack length
% %
% % FREE (solved for):
% %   d     rack's position from front axle
% %   t     tie-rod length
% %   s     steering-arm length
% %   toe0  net static offset (see MechanismDeltas.m header for why
% %         "steering arm angle" and "toe at zero steer" are combined
% %         into this single parameter)
% %
% % Requires Optimization Toolbox (lsqnonlin). If you don't have it,
% % swap the call at the bottom for the fminsearch fallback noted below.
% %-------------------------------------------------------------
% 
% a = car.t2;
% r = car.r;
% 
% targetInner = abs(rad2deg([Result.delta_fi]'));
% targetOuter = abs(rad2deg([Result.delta_fo]'));
% 
% % ---------------------------------------------------------------
% % EDIT THESE: initial guess and bounds
% %              [   d      t      s     toe0 ]   (m, m, m, deg)
% p0   =        [ 0.15,  0.30,  0.12,    0   ];
% lb   =        [ 0.05,  0.15,  0.05,   -3   ];
% ub   =        [ 0.40,  0.60,  0.25,    3   ];
% % ---------------------------------------------------------------
% 
% objFun = @(p) MechanismResiduals(p, a, r, targetInner, targetOuter);
% 
% opts = optimoptions('lsqnonlin', ...
%     'Display','iter', ...
%     'FunctionTolerance',1e-10, ...
%     'StepTolerance',1e-10);
% 
% [pBest, resnorm, residual, exitflag] = lsqnonlin(objFun, p0, lb, ub, opts);
% 
% % --- If you don't have Optimization Toolbox, comment the block above
% %     and use this instead (minimizes sum of squared residuals with
% %     plain MATLAB fminsearch - no bounds support, so keep p0 sane):
% %
% % costFun = @(p) sum(MechanismResiduals(p, a, r, targetInner, targetOuter).^2);
% % pBest = fminsearch(costFun, p0);
% % residual = MechanismResiduals(pBest, a, r, targetInner, targetOuter);
% % resnorm = sum(residual.^2);
% % exitflag = NaN;
% 
% best.d    = pBest(1);
% best.t    = pBest(2);
% best.s    = pBest(3);
% best.toe0 = pBest(4);
% best.a    = a;
% best.r    = r;
% 
% n = numel(targetInner);
% fitInfo.targetInner   = targetInner;
% fitInfo.targetOuter   = targetOuter;
% fitInfo.achievedInner = zeros(n,1);
% fitInfo.achievedOuter = zeros(n,1);
% fitInfo.rackDisp      = zeros(n,1);
% fitInfo.reachable     = true(n,1);
% 
% for i = 1:n
%     [x_i, achI, achO, reach] = SolveRackForInner(targetInner(i), pBest, a, r);
%     fitInfo.rackDisp(i)      = x_i;
%     fitInfo.achievedInner(i) = achI;
%     fitInfo.achievedOuter(i) = achO;
%     fitInfo.reachable(i)     = reach;
% end
% 
% fitInfo.resnorm  = resnorm;
% fitInfo.residual = residual;
% fitInfo.exitflag = exitflag;
% 
% fprintf('\n--- Steering Mechanism Synthesis ---\n');
% fprintf('d (rack pos. from axle) = %.4f m\n', best.d);
% fprintf('t (tie-rod length)      = %.4f m\n', best.t);
% fprintf('s (arm length)          = %.4f m\n', best.s);
% fprintf('toe0 (net offset)       = %.3f deg\n', best.toe0);
% fprintf('RMS error (inner+outer) = %.4f deg\n', sqrt(mean(residual.^2)));
% if any(~fitInfo.reachable)
%     fprintf(2,'Warning: %d of %d target radii are NOT fully reachable with this geometry (mechanism saturates).\n', ...
%         sum(~fitInfo.reachable), n);
% end
% fprintf('-------------------------------------\n\n');
% 
% PlotMechanismFit(car, fitInfo);
% 
% end



























function [best, fitInfo] = SteeringSynthesis(car, Result)
%-------------------------------------------------------------
% Synthesizes a rack/tie-rod/steering-arm mechanism that best
% reproduces the target delta_fi / delta_fo curves from the vehicle
% solver, in a least-squares sense.
%
% FIXED (not solved for - come from suspension/rack design):
%   a = car.t2   distance between steering-arm fixed pivots
%   r = car.r    rack length
%
% FREE (solved for):
%   d       rack's position from front axle
%   t       tie-rod length
%   s       steering-arm length
%   toe0    net static offset (see MechanismDeltas.m header for why
%           "steering arm angle" and "toe at zero steer" are combined
%           into this single parameter)
%   x_1..n  rack displacement AT EACH target radius (one per radius)
%
% Why x floats per radius: a single rack position determines BOTH the
% inner and outer angle at once, so for a target curve that wasn't
% generated by this exact mechanism, you generally can't hit both
% exactly - only one, or a compromise. Forcing the inner angle exact
% (an earlier approach) dumps all the leftover error onto the outer
% angle. Letting x float per radius lets the optimizer share the
% error between inner and outer however minimizes the total, which
% is a fairer and usually much tighter fit.
%
% Requires Optimization Toolbox (lsqnonlin). If you don't have it,
% swap the call below for the fminsearch fallback noted at the bottom.
%-------------------------------------------------------------

a = car.t2;
r = car.r;

targetInner = abs(rad2deg([Result.delta_fi]'));
targetOuter = abs(rad2deg([Result.delta_fo]'));
n = numel(targetInner);

% ---------------------------------------------------------------
% EDIT THESE: initial guess and bounds for the shared mechanism
%             parameters                 [   d      t      s     toe0 ]
p0   =        [ 0.15,  0.30,  0.12,    0   ];
p_lb =        [ 0.05,  0.15,  0.05,   -3   ];
p_ub =        [ 0.40,  0.60,  0.25,    3   ];

% EDIT: rough scale for rack travel, just used to seed the initial
%       guess for x - the optimizer will move these freely within
%       [x_lb, x_ub] regardless of how good this guess is.
xGuessMax = 0.08;   % m
% ---------------------------------------------------------------

x0   = xGuessMax * (targetInner(:) / max(targetInner));
x_lb = zeros(n,1);
x_ub = 0.5*ones(n,1);      % m - generous upper bound on rack travel

z0 = [p0(:); x0];
lb = [p_lb(:); x_lb];
ub = [p_ub(:); x_ub];

objFun = @(z) MechanismResidualsJoint(z, a, r, targetInner, targetOuter);

opts = optimoptions('lsqnonlin', ...
    'Display','iter', ...
    'FunctionTolerance',1e-12, ...
    'StepTolerance',1e-12, ...
    'MaxFunctionEvaluations', 5000);

[zBest, resnorm, residual, exitflag] = lsqnonlin(objFun, z0, lb, ub, opts);

% --- If you don't have Optimization Toolbox, comment the block above
%     and use this instead (minimizes sum of squared residuals with
%     plain MATLAB fminsearch - no bounds support, so keep z0 sane):
%
% costFun = @(z) sum(MechanismResidualsJoint(z, a, r, targetInner, targetOuter).^2);
% zBest = fminsearch(costFun, z0);
% residual = MechanismResidualsJoint(zBest, a, r, targetInner, targetOuter);
% resnorm = sum(residual.^2);
% exitflag = NaN;

pBest = zBest(1:4);
xBest = zBest(5:end);

best.d    = pBest(1);
best.t    = pBest(2);
best.s    = pBest(3);
best.toe0 = pBest(4);
best.a    = a;
best.r    = r;

[achInner, achOuter] = MechanismDeltas(pBest, a, r, xBest);

fitInfo.targetInner   = targetInner;
fitInfo.targetOuter   = targetOuter;
fitInfo.achievedInner = achInner(:);
fitInfo.achievedOuter = achOuter(:);
fitInfo.rackDisp      = xBest;
fitInfo.reachable     = true(n,1);   % kept for PlotMechanismFit compatibility
fitInfo.resnorm       = resnorm;
fitInfo.residual      = residual;
fitInfo.exitflag      = exitflag;

fprintf('\n--- Steering Mechanism Synthesis (joint fit) ---\n');
fprintf('d (rack pos. from axle) = %.2f mm\n', best.d*1000);
fprintf('t (tie-rod length)      = %.2f mm\n', best.t*1000);
fprintf('s (arm length)          = %.2f mm\n', best.s*1000);
fprintf('toe0 (net offset)       = %.3f deg\n', best.toe0);
fprintf('RMS error (inner+outer) = %.4f deg\n', sqrt(mean(residual.^2)));
fprintf('Max abs error           = %.4f deg\n', max(abs(residual)));
fprintf('---------------------------------------------------\n\n');

PlotMechanismFit(car, fitInfo);

end